import { createServer } from 'node:http'
import { readFile, stat, mkdir } from 'node:fs/promises'
import { resolve, extname } from 'node:path'
import { chromium } from '@playwright/test'

const root = resolve('dist')
const server = createServer(async (req, res) => {
  try {
    let path = resolve(root, '.' + new URL(req.url, 'http://localhost').pathname)
    if (!path.startsWith(root)) { res.writeHead(403); res.end(); return }
    try { if ((await stat(path)).isDirectory()) path = resolve(path, 'index.html') } catch { path = resolve(root, 'index.html') }
    const contents = await readFile(path)
    const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.webp': 'image/webp', '.svg': 'image/svg+xml', '.woff2': 'font/woff2' }
    res.writeHead(200, { 'Content-Type': types[extname(path)] || 'application/octet-stream' }); res.end(contents)
  } catch { res.writeHead(404); res.end() }
})
await new Promise(r => server.listen(0, '127.0.0.1', r))
const base = `http://127.0.0.1:${server.address().port}`
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] })
const failures = []
const check = (name, condition) => { console.log(`${condition ? 'PASS' : 'FAIL'}: ${name}`); if (!condition) failures.push(name) }
await mkdir('artifacts', { recursive: true })
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 }, deviceScaleFactor: 1 })
  page.on('pageerror', error => failures.push(error.message))
  await page.goto(base)
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true })
  check('No desktop horizontal overflow', await page.evaluate(() => document.documentElement.scrollWidth === window.innerWidth))
  check('Original fonts loaded', await page.evaluate(() => document.fonts.check('16px "Bebas Neue"') && document.fonts.check('16px "Inter"')))
  check('Hero screens load', await page.locator('.phone-frame img').evaluateAll(images => images.every(image => image.complete && image.naturalWidth > 0)))
  check('Feature cards render without the removed section intro', await page.locator('.features-section').evaluate(section => section.querySelector('.section-heading') === null && section.querySelectorAll('.feature-item').length === 4))
  await page.getByRole('button', { name: 'Next app screenshot' }).click()
  check('Carousel advances', await page.locator('.carousel-center p').textContent() === 'Your entire tour, at a glance')
  await page.getByRole('button', { name: 'Previous app screenshot' }).click()
  await page.getByRole('button', { name: 'How-to guides' }).click()
  check('Guide menu expands', await page.locator('#guide-dropdown').isVisible())
  await page.locator('#guide-dropdown').evaluate(el => Promise.all(el.getAnimations().map(animation => animation.finished)))
  await page.screenshot({ path: 'artifacts/menu.png' })
  await page.locator('#guide-dropdown').getByRole('link', { name: /Share calendar with family/ }).click()
  await page.waitForURL('**/guides/share-calendar')
  await page.locator('.guide-step').first().waitFor()
  check('Share guide has steps', await page.locator('.guide-step').count() === 5)
  await page.getByRole('button', { name: 'Mark complete: Find Share Calendar in Settings', exact: true }).click()
  check('Guide progress tracks completion', await page.locator('.guide-progress').textContent().then(s => s.includes('1 of 5')))
  await page.reload()
  check('Guide progress persists', await page.locator('.guide-progress').textContent().then(s => s.includes('1 of 5')))
  await page.getByRole('button', { name: 'How do I stop sharing?' }).click()
  check('FAQ opens', await page.locator('.faq-item.open p').isVisible())
  await page.locator('.step-image').first().click()
  check('Screenshot zoom opens', await page.getByRole('dialog').isVisible())
  await page.keyboard.press('Escape')
  check('Screenshot zoom closes on Escape', await page.getByRole('dialog').count() === 0)
  await page.goto(base + '/guides')
  await page.getByRole('textbox', { name: 'Search how-to guides' }).fill('mutuals')
  check('Guide search filters', await page.locator('.library-card').count() === 1)
  await page.getByRole('textbox', { name: 'Search how-to guides' }).fill('no such guide')
  check('Search empty state', await page.locator('.empty-search').isVisible())
  await page.getByRole('button', { name: 'Show all guides' }).click()
  check('Clear search restores all three guides', await page.locator('.library-card').count() === 3)
  await page.getByRole('button', { name: 'Calendar', exact: true }).click()
  check('Category filters', await page.locator('.library-card').count() === 1)
  await page.goto(base + '/guides/send-mxp-mutuals')
  check('MXP guide has four steps', await page.locator('.guide-step').count() === 4)
  await page.screenshot({ path: 'artifacts/guide.png' })
  await page.evaluate(() => localStorage.removeItem('fdny-howto3-checks'))
  await page.goto(base + '/guides/overtime-equalization')
  check('MSOT guide has four steps', await page.locator('.msot-guide-step').count() === 4)
  check('MSOT guide marks the active step in both rails', await page.locator('.msot-guide__rail a[aria-current="step"]').count() === 1 && await page.locator('.msot-guide__mobile-rail a[aria-current="step"]').count() === 1)
  await page.getByRole('button', { name: /Enlarge:.*Scan New OT Report/ }).click()
  check('MSOT screenshot dialog opens', await page.getByRole('dialog').isVisible())
  await page.keyboard.press('Escape')
  check('MSOT screenshot dialog closes on Escape', await page.getByRole('dialog').count() === 0)
  const calendarHours = page.getByRole('slider', { name: 'Calendar hours' })
  await calendarHours.fill('28')
  check('MSOT simulator reports higher calendar hours', await page.locator('.msot-simulator-status').textContent().then(text => text?.includes('CALENDAR HIGHER')))
  check('MSOT simulator announces changed calendar hours', (await calendarHours.getAttribute('aria-valuetext'))?.includes('28 calendar hours; calendar higher'))
  await calendarHours.fill('24')
  check('MSOT simulator reports matching hours', await page.locator('.msot-simulator-status').textContent().then(text => text?.includes('HOURS MATCH')))
  await page.getByRole('button', { name: /Tapped “Scan New OT Report”/ }).click()
  check('MSOT checklist tracks completion', await page.locator('.msot-checklist-progress').textContent().then(text => text?.includes('1 of 6 done')))
  await page.reload()
  check('MSOT checklist progress persists after reload', await page.locator('.msot-checklist-progress').textContent().then(text => text?.includes('1 of 6 done')))
  const msotFaq = page.getByRole('button', { name: 'What if the scanner reads the wrong total?' })
  await msotFaq.click()
  check('MSOT FAQ opens', await msotFaq.getAttribute('aria-expanded') === 'true' && await page.locator('#msot-faq-answer-0').isVisible())
  await msotFaq.click()
  check('MSOT FAQ closes', await msotFaq.getAttribute('aria-expanded') === 'false' && await page.locator('#msot-faq-answer-0').count() === 0)
  await page.goto(base)
  await page.locator('.nav-feedback').click()
  check('Feedback modal opens', await page.getByRole('dialog').isVisible())
  await page.screenshot({ path: 'artifacts/feedback.png' })
  await page.getByRole('button', { name: 'Bug report', exact: true }).click()
  await page.getByLabel('Your name').fill('Interface Test')
  await page.getByLabel('Email address').fill('test@example.com')
  await page.getByLabel('Your message').fill('This is a mocked feedback submission for interface testing only.')
  await page.route('https://formsubmit.co/ajax/**', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"success":false}' }))
  await page.locator('.submit-feedback').click()
  await page.getByRole('alert').waitFor()
  check('Feedback error shown without losing message', await page.getByRole('alert').isVisible() && (await page.getByLabel('Your message').inputValue()).length > 10)
  await page.unroute('https://formsubmit.co/ajax/**')
  await page.route('https://formsubmit.co/ajax/**', route => route.fulfill({ status: 200, contentType: 'application/json', body: '{"success":"true"}' }))
  await page.locator('.submit-feedback').click()
  await page.locator('.feedback-success').waitFor()
  check('Feedback success state displays', await page.locator('.feedback-success').isVisible())
  await page.getByRole('button', { name: 'Back to the app' }).click()
  check('Feedback closes', await page.getByRole('dialog').count() === 0)
  await page.goto(base + '/how-to-share-calendar.html')
  await page.waitForURL('**/guides/share-calendar')
  check('Original URLs redirect to new guides', page.url().endsWith('/guides/share-calendar'))
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true })
  mobile.on('pageerror', error => failures.push(error.message))
  await mobile.goto(base)
  await mobile.evaluate(() => document.fonts.ready)
  await mobile.screenshot({ path: 'artifacts/mobile.png', fullPage: true })
  check('No mobile horizontal overflow', await mobile.evaluate(() => document.documentElement.scrollWidth === window.innerWidth))
  await mobile.getByRole('button', { name: 'How-to guides' }).click()
  const bounds = await mobile.locator('#guide-dropdown').boundingBox()
  check('Mobile guide dropdown stays on screen', bounds.x >= 0 && bounds.x + bounds.width <= 390)
  await mobile.getByRole('link', { name: 'Explore all how-to guides' }).click()
  await mobile.waitForURL('**/guides')
  await mobile.locator('.library-card').first().waitFor()
  check('Mobile guide library loads all three guides', await mobile.locator('.library-card').count() === 3)
  await mobile.locator('.nav-feedback').click()
  check('Mobile feedback fits viewport', await mobile.getByRole('dialog').evaluate(el => el.getBoundingClientRect().width <= window.innerWidth))
  await mobile.screenshot({ path: 'artifacts/mobile-feedback.png' })
  const narrow = await browser.newPage({ viewport: { width: 320, height: 720 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true })
  await mobile.goto(base + '/guides/overtime-equalization')
  check('MSOT guide has no 390px horizontal overflow', await mobile.evaluate(() => document.documentElement.scrollWidth === window.innerWidth))
  await narrow.goto(base + '/guides/overtime-equalization')
  check('MSOT guide has no 320px horizontal overflow', await narrow.evaluate(() => document.documentElement.scrollWidth === window.innerWidth))
  console.log('RESULT:', failures.length ? failures : 'All checks passed')
} finally { await browser.close(); server.close() }
if (failures.length) process.exitCode = 1
