import { createServer } from 'node:http'
import { readFile, stat, mkdir } from 'node:fs/promises'
import { resolve, extname } from 'node:path'
import { chromium } from '@playwright/test'

const root = resolve('dist')
const server = createServer(async (req, res) => {
  try {
    let path = resolve(root, '.' + new URL(req.url, 'http://localhost').pathname)
    if (!path.startsWith(root)) { res.writeHead(403); res.end(); return }
    try { if ((await stat(path)).isDirectory()) path = resolve(path, 'index.html') } catch { path = resolve(root, 'index.html') }
    const contents = await readFile(path)
    const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.webp': 'image/webp', '.svg': 'image/svg+xml', '.woff2': 'font/woff2' }
    res.writeHead(200, { 'Content-Type': types[extname(path)] || 'application/octet-stream' }); res.end(contents)
  } catch { res.writeHead(404); res.end() }
})
await new Promise(r => server.listen(0, '127.0.0.1', r))
const base = `http://127.0.0.1:${server.address().port}`
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] })
const failures = []
const check = (name, condition) => { console.log(`${condition ? 'PASS' : 'FAIL'}: ${name}`); if (!condition) failures.push(name) }
await mkdir('artifacts', { recursive: true })
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 }, deviceScaleFactor: 1 })
  page.on('pageerror', error => failures.push(error.message))
  await page.goto(base)
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: 'artifacts/desktop.png', fullPage: true })
  check('No desktop horizontal overflow', await page.evaluate(() => document.documentElement.scrollWidth === window.innerWidth))
  check('Original fonts loaded', await page.evaluate(() => document.fonts.check('16px "Bebas Neue"') && document.fonts.check('16px "Inter"')))
  check('Hero screens load', await page.locator('.phone-frame img').evaluateAll(images => images.every(image => image.complete && image.naturalWidth > 0)))
  check('Feature cards render without the removed section intro', await page.locator('.features-section').evaluate(section => section.querySelector('.section-heading') === null && section.querySelectorAll('.feature-item').length === 4))
  await page.getByRole('button', { name: 'Next app screenshot' }).click()
  check('Carousel advances', await page.locator('.carousel-center p').textContent() === 'Your entire tour, at a glance')
  await page.getByRole('button', { name: 'Previous app screenshot' }).click()
  await page.getByRole('button', { name: 'How-to guides' }).click()
  check('Guide menu expands', await page.locator('#guide-dropdown').isVisible())
  await page.locator('#guide-dropdown').evaluate(el => Promise.all(el.getAnimations().map(animation => animation.finished)))
  await page.screenshot({ path: 'artifacts/menu.png' })
  await page.locator('#guide-dropdown').getByRole('link', { name: /Share calendar with family/ }).click()
  await page.waitForURL('**/guides/share-calendar')
  await page.locator('.guide-step').first().waitFor()
  check('Share guide has steps', await page.locator('.guide-step').count() === 5)
  await page.getByRole('button', { name: 'Mark complete: Find Share Calendar in Settings', exact: true }).click()
  check('Guide progress tracks completion', await page.locator('.guide-progress').textContent().then(s => s.includes('1 of 5')))
  await page.reload()
  check('Guide progress persists', await page.locator('.guide-progress').textContent().then(s => s.includes('1 of 5')))
  await page.getByRole('button', { name: 'How do I stop sharing?' }).click()
  check('FAQ opens', await page.locator('.faq-item.open p').isVisible())
  await page.locator('.step-image').first().click()
  check('Screenshot zoom opens', await page.getByRole('dialog').isVisible())
  await page.keyboard.press('Escape')
  check('Screenshot zoom closes on Escape', await page.getByRole('dialog').count() === 0)
  await page.goto(base + '/guides')
  await page.getByRole('textbox', { name: 'Search how-to guides' }).fill('mutuals')
  check('Guide search filters', await page.locator('.library-card').count() === 1)
  await page.getByRole('textbox', { name: 'Search how-to guides' }).fill('no such guide')
  check('Search empty state', await page.locator('.empty-search').isVisible())
  await page.getByRole('button', { name: 'Show all guides' }).click()
  check('Clear search restores all three guides', await page.locator('.library-card').count() === 3)
  await page.getByRole('button', { name: 'Calendar', exact: true }).click()
  check('Category filters', await page.locator('.library-card').count() === 1)
  await page.goto(base + '/guides/send-mxp-mutuals')
  check('MXP guide has four steps', await page.locator('.guide-step').count() === 4)
  await page.screenshot({ path: 'artifacts/guide.png' })
  await page.evaluate(() => localStorage.removeItem('fdny-howto3-checks'))
  await page.goto(base + '/guides/overtime-equalization')
  check('MSOT guide has four steps', await page.locator('.msot-guide-step').count() === 4)
  check('MSOT guide marks the active step in both rails', await page.locator('.msot-guide__rail a[aria-current="step"]').count() === 1 && await page.locator('.msot-guide__mobile-rail a[aria-current="step"]').count() === 1)
  await page.getByRole('button', { name: /Enlarge:.*Scan New OT Report/ }).click()
  check('MSOT screenshot dialog opens', await page.getByRole('dialog').isVisible())
  await page.keyboard.press('Escape')
  check('MSOT screenshot dialog closes on Escape', await page.getByRole('dialog').count() === 0)
  const calendarHours = page.getByRole('slider', { name: 'Calendar hours' })
  await calendarHours.fill('28')
  check('MSOT simulator reports higher calendar hours', await page.locator('.msot-simulator-status').textContent().then(text => text?.includes('CALENDAR HIGHER')))
  check('MSOT simulator announces changed calendar hours', (await calendarHours.getAttribute('aria-valuetext'))?.includes('28 calendar hours; calendar higher'))
  await calendarHours.fill('24')
  check('MSOT simulator reports matching hours', await page.locator('.msot-simulator-status').textContent().then(text => text?.includes('HOURS MATCH')))
  await page.getByRole('button', { name: /Tapped “Scan New OT Report”/ }).click()
  check('MSOT checklist tracks completion', await page.locator('.msot-checklist-progress').textContent().then(text => text?.includes('1 of 6 done')))
  await page.reload()
  check('MSOT checklist progress persists after reload', await page.locator('.msot-checklist-progress').textContent().then(text => text?.includes('1 of 6 done')))
  const msotFaq = page.getByRole('button', { name: 'What if the scanner reads the wrong total?' })
  await msotFaq.click()
  check('MSOT FAQ opens', await msotFaq.getAttribute('aria-expanded') === 'true' && await page.locator('#msot-faq-answer-0').isVisible())
  await msotFaq.click()
  check('MSOT FAQ closes', await msotFaq.getAttribute('aria-expanded') === 'false' && await page.locator('#msot-faq-answer-0').count() === 0)
  await page.goto(base)
  await page.locator('.nav-feedback').click()
  check('Feedback modal opens', await page.getByRole('dialog').isVisible())
  await page.screenshot({ path: 'artifacts/feedback.png' })
  await page.getByRole('button', { name: 'Bug report', exact: true }).click()
  await page.getByLabel('Your name').fill('Interface Test')
  await page.getByLabel('Email address').fill('test@example.com')
  await page.getByLabel('Your message').fill('This is a mocked feedback submission for interface testing only.')
  await page.route('https://formsubmit.co/ajax/**', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"success":false}' }))
  await page.locator('.submit-feedback').click()
  await page.getByRole('alert').waitFor()
  check('Feedback error shown without losing message', await page.getByRole('alert').isVisible() && (await page.getByLabel('Your message').inputValue()).length > 10)
  await page.unroute('https://formsubmit.co/ajax/**')
  await page.route('https://formsubmit.co/ajax/**', route => route.fulfill({ status: 200, contentType: 'application/json', body: '{"success":"true"}' }))
  await page.locator('.submit-feedback').click()
  await page.locator('.feedback-success').waitFor()
  check('Feedback success state displays', await page.locator('.feedback-success').isVisible())
  await page.getByRole('button', { name: 'Back to the app' }).click()
  check('Feedback closes', await page.getByRole('dialog').count() === 0)
  await page.goto(base + '/how-to-share-calendar.html')
  await page.waitForURL('**/guides/share-calendar')
  check('Original URLs redirect to new guides', page.url().endsWith('/guides/share-calendar'))
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true })
  mobile.on('pageerror', error => failures.push(error.message))
  await mobile.goto(base)
  await mobile.evaluate(() => document.fonts.ready)
  await mobile.screenshot({ path: 'artifacts/mobile.png', fullPage: true })
  check('No mobile horizontal overflow', await mobile.evaluate(() => document.documentElement.scrollWidth === window.innerWidth))
  await mobile.getByRole('button', { name: 'How-to guides' }).click()
  const bounds = await mobile.locator('#guide-dropdown').boundingBox()
  check('Mobile guide dropdown stays on screen', bounds.x >= 0 && bounds.x + bounds.width <= 390)
  await mobile.getByRole('link', { name: 'Explore all how-to guides' }).click()
  await mobile.waitForURL('**/guides')
  await mobile.locator('.library-card').first().waitFor()
  check('Mobile guide library loads all three guides', await mobile.locator('.library-card').count() === 3)
  await mobile.locator('.nav-feedback').first().click()
  check('Mobile feedback fits viewport', await mobile.getByRole('dialog').evaluate(el => el.getBoundingClientRect().width <= window.innerWidth))
  await mobile.screenshot({ path: 'artifacts/mobile-feedback.png' })
  const narrow = await browser.newPage({ viewport: { width: 320, height: 720 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true })
  await mobile.goto(base + '/guides/overtime-equalization')
  check('MSOT guide has no 390px horizontal overflow', await mobile.evaluate(() => document.documentElement.scrollWidth === window.innerWidth))
  await narrow.goto(base + '/guides/overtime-equalization')
  check('MSOT guide has no 320px horizontal overflow', await narrow.evaluate(() => document.documentElement.scrollWidth === window.innerWidth))
  const sim = await browser.newPage({ viewport: { width: 1280, height: 1000 }, deviceScaleFactor: 1 })
  sim.on('pageerror', error => failures.push(error.message))
  await sim.goto(base + '/app-simulator')
  await sim.locator('.sim-bottom-tabs').waitFor()
  await sim.locator('.sim-bottom-tabs button', { hasText: 'Calendar' }).first().click()
  await sim.locator('.sim-segments button', { hasText: 'MONTH' }).first().click()
  await sim.locator('.sim-reference-day.is-today').click()
  await sim.locator('.sim-day-sheet').waitFor()
  check('Simulator month day opens roster sheet', await sim.locator('.sim-roster').isVisible())
  check('Day sheet lists every add-to-day action', await sim.locator('.sim-day-sheet .sim-sheet-btn').count() >= 13)
  check('Ordinary days show no mutual pick section', await sim.locator('.sim-day-sheet .sim-pick-card').count() === 0)
  const eventsBefore = await sim.locator('.sim-day-sheet .sim-event').count()
  await sim.locator('.sim-day-sheet .sim-sheet-btn', { hasText: 'RSOT 9x' }).first().click()
  check('Day sheet add confirms with toast', await sim.locator('.sim-toast.is-visible').waitFor().then(() => true).catch(() => false))
  check('Day sheet add creates a visible entry', await sim.locator('.sim-day-sheet .sim-event').count() === eventsBefore + 1)
  await sim.reload()
  await sim.locator('.sim-bottom-tabs').waitFor()
  await sim.locator('.sim-bottom-tabs button', { hasText: 'Calendar' }).first().click()
  await sim.locator('.sim-segments button', { hasText: 'MONTH' }).first().click()
  await sim.locator('.sim-reference-day.is-today').click()
  check('Day sheet entry persists after reload', await sim.locator('.sim-day-sheet .sim-event').count() === eventsBefore + 1)
  check('Line-up days are marked with a red dot', await sim.locator('.sim-reference-mx-dot').first().isVisible())
  await sim.keyboard.press('Escape')
  await sim.getByRole('button', { name: /Sep 15, 2026, mutual opportunity/ }).click()
  await sim.locator('.sim-pick-grid').waitFor()
  check('Line-up day sheet asks which set you are working', await sim.locator('.sim-day-sheet').getByText('Which set are you working?').isVisible())
  check('Mutual pick section offers all four sets', await sim.locator('.sim-pick-card').count() === 4)
  const mxInSheet = await sim.locator('.sim-day-sheet .sim-event').count()
  await sim.locator('.sim-pick-card', { hasText: 'Insides' }).click()
  check('Picking a set confirms with a toast', await sim.locator('.sim-toast.is-visible').waitFor().then(() => true).catch(() => false))
  check('Picking a set logs the mutual entry on that day', await sim.locator('.sim-day-sheet .sim-event').count() === mxInSheet + 1)
  await sim.keyboard.press('Escape')
  for (let i = 0; i < 4; i++) { await sim.locator('.sim-bottom-tabs button', { hasText: 'Calendar' }).first().click(); await sim.waitForTimeout(60) }
  check('Repeated bottom-tab taps keep the active tab stable', await sim.locator('.sim-bottom-tabs button[aria-pressed=true] span').textContent().then(t => t === 'Calendar') && await sim.locator('.sim-app-header h2').textContent().then(t => t === 'Calendar'))
  await sim.locator('.sim-bottom-tabs button', { hasText: 'Tracker' }).first().click()
  await sim.locator('.sim-bottom-tabs button', { hasText: 'Tracker' }).first().click()
  check('Repeated taps land on the requested tab', await sim.locator('.sim-app-header h2').textContent().then(t => t === 'Tracker'))
  await sim.close()
  await page.goto(base)
  const simulatorLink = page.getByRole('link', { name: 'Try the app simulator', exact: true })
  check('Homepage links to the simulator', await simulatorLink.getAttribute('href') === '/app-simulator')
  await simulatorLink.click()
  await page.waitForURL('**/app-simulator')
  await page.getByRole('heading', { name: 'Your next tour. Try it here.' }).waitFor()
  check('Simulator navigation from homepage works', await page.getByRole('heading', { name: 'Your next tour. Try it here.' }).isVisible())
  const demo = await browser.newPage({ viewport: { width: 1440, height: 1100 } })
  const externalRequests = []
  const backendRequests = []
  demo.on('request', request => { if (['fetch', 'xhr', 'websocket', 'ping'].includes(request.resourceType()) || request.method() !== 'GET') backendRequests.push(request.url()) })
  demo.on('pageerror', error => failures.push(error.message))
  await demo.route('**/*', route => {
    if (!route.request().url().startsWith(base)) { externalRequests.push(route.request().url()); return route.abort() }
    return route.continue()
  })
  const response = await demo.goto(base + '/app-simulator/')
  await demo.locator('.sim-device').waitFor()
  check('Simulator loads its direct static route', response.status() === 200 && await demo.locator('.sim-device').isVisible())
  await demo.getByRole('button', { name: 'Dismiss sync warning' }).click()
  await demo.getByRole('button', { name: 'MONTH', exact: true }).click()
  await demo.locator('.sim-device').screenshot({ path: 'artifacts/simulator-month-desktop.png' })
  check('Month calendar starts on Sunday', await demo.locator('.sim-reference-weekdays span').first().textContent() === 'SUN')
  await demo.getByRole('button', { name: 'Sep 12, 2026, 2 entries', exact: true }).click()
  check('Clicking a month day opens its entries in a modal', await demo.getByRole('dialog').isVisible() && await demo.getByRole('dialog').getByText('MSOT 9x', { exact: true }).isVisible())
  await demo.keyboard.press('Escape')
  check('Month day modal closes on Escape and restores day focus', await demo.getByRole('button', { name: 'Sep 12, 2026, 2 entries', exact: true }).evaluate(el => el === document.activeElement))
  await demo.getByRole('button', { name: 'Sep 1, 2026', exact: true }).press('Enter')
  check('Keyboard opens an empty month day', await demo.getByRole('dialog').getByText('ADD TO THIS DAY', { exact: true }).isVisible() && await demo.locator('.sim-day-sheet .sim-event').count() === 0)
  await demo.getByRole('button', { name: 'RSOT 9x' }).first().click()
  check('Day sheet quick-add creates an entry on the tapped date', await demo.locator('.sim-day-sheet .sim-event').filter({ hasText: 'RSOT 9x' }).count() === 1)
  await demo.keyboard.press('Escape')
  await demo.getByRole('button', { name: 'TODAY', exact: true }).click()
  await demo.getByRole('button', { name: 'WEEK', exact: true }).click()
  await demo.getByRole('button', { name: 'Add calendar entry', exact: true }).click()
  await demo.getByLabel('Entry type', { exact: true }).selectOption('Vacation')
  await demo.getByLabel('Entry date', { exact: true }).fill('2026-09-12')
  await demo.getByLabel('Vacation selection', { exact: true }).selectOption('Swapped')
  await demo.getByRole('button', { name: 'Save demo entry' }).click()
  check('Calendar adds a fictional entry', await demo.locator('.sim-event').filter({ hasText: 'Vacation' }).count() === 1)
  await demo.reload()
  check('Vacation choice persists after reload', await demo.locator('.sim-event').filter({ hasText: 'Vacation' }).textContent().then(t => t.includes('Swapped')))
  check('Demo entry persists after reload', await demo.locator('.sim-event').filter({ hasText: 'Vacation' }).count() === 1)
  await demo.locator('.sim-event').filter({ hasText: 'Vacation' }).getByRole('button', { name: /View/ }).click()
  await demo.getByRole('button', { name: 'Mark complete' }).click()
  check('Leave can be completed', await demo.locator('.sim-event').filter({ hasText: 'Vacation' }).textContent().then(t => t.includes('Complete')))
  await demo.getByRole('button', { name: 'Tracker', exact: true }).click()
  await demo.getByRole('button', { name: 'MUTUALS', exact: true }).click()
  await demo.getByRole('button', { name: /Joe Floorbelow.*View mutual history/ }).click()
  check('Mutual partner detail opens', await demo.getByRole('heading', { name: 'Joe Floorbelow', exact: true }).isVisible())
  await demo.getByRole('button', { name: 'Open mutual request' }).click()
  await demo.getByLabel('Mutual status').selectOption('Accepted')
  await demo.getByRole('button', { name: 'Save demo status' }).click()
  check('Mutual status changes', await demo.getByRole('button', { name: 'Open mutual request' }).textContent().then(t => t.includes('Accepted')))
  await demo.getByRole('button', { name: 'My Crew', exact: true }).click()
  check('Crew shows fictional demo user', await demo.locator('.sim-screen').textContent().then(t => t.includes('Johnny Staylow')))
  await demo.getByRole('button', { name: 'Settings', exact: true }).click()
  await demo.getByText('01 IDENTITY & CREW', { exact: true }).click()
  await demo.getByRole('button', { name: 'Officer', exact: true }).click()
  await demo.reload()
  await demo.getByRole('button', { name: 'Settings', exact: true }).click()
  await demo.getByText('01 IDENTITY & CREW', { exact: true }).click()
  check('Rank persists', await demo.getByRole('button', { name: 'Officer', exact: true }).getAttribute('aria-pressed') === 'true')
  await demo.getByRole('button', { name: 'Tracker', exact: true }).click()
  await demo.getByRole('button', { name: 'MUTUALS', exact: true }).click()
  await demo.getByRole('button', { name: 'View MX Off on Sep 13, 2026' }).click()
  await demo.getByRole('button', { name: 'Remove demo entry' }).click()
  check('Removing a mutual updates the balance', await demo.locator('.sim-balance > strong').textContent() === '0')
  await demo.getByRole('button', { name: 'OT LOG', exact: true }).click()
  await demo.getByRole('button', { name: 'Add overtime entry' }).click()
  await demo.getByLabel('Entry type', { exact: true }).selectOption('Awaiting Relief')
  await demo.getByLabel('Duration', { exact: true }).fill('30')
  await demo.getByLabel('Duration unit', { exact: true }).selectOption('minutes')
  await demo.getByRole('button', { name: 'Save demo entry' }).click()
  await demo.locator('.sim-accordion summary').filter({ hasText: 'Sep 6' }).click()
  check('Custom overtime duration is reflected in the chip', await demo.locator('.sim-chip').filter({ hasText: 'AR 30m' }).isVisible())
  await demo.getByRole('button', { name: 'Add overtime entry' }).click()
  await demo.getByLabel('Duration', { exact: true }).fill('100')
  await demo.getByRole('button', { name: 'Save demo entry' }).click()
  await demo.getByRole('button', { name: 'STATS', exact: true }).click()
  await demo.getByRole('button', { name: 'Match demo report to calendar' }).click()
  check('OT equalization reports a match', await demo.locator('.sim-report-status').textContent().then(t => t.includes('HOURS MATCH')))
  await demo.reload()
  await demo.getByRole('button', { name: 'Tracker', exact: true }).click()
  await demo.getByRole('button', { name: 'STATS', exact: true }).click()
  check('Large OT reports persist without resetting the demo', await demo.getByRole('slider', { name: 'Demo report hours' }).inputValue() === '124')
  await demo.getByRole('slider', { name: 'Demo report hours' }).fill('123')
  check('Equalization responds to report edits', await demo.locator('.sim-report-status').textContent().then(t => t.includes('CALENDAR HIGHER')))
  await demo.getByRole('button', { name: 'SCHEDULE', exact: true }).click()
  await demo.getByRole('button', { name: 'RSOT Dates', exact: true }).click()
  await demo.getByRole('button', { name: 'Apply dates to demo calendar' }).click()
  check('Applying RSOT dates does not duplicate the seeded tour', await demo.evaluate(() => JSON.parse(localStorage.getItem('fdnymx.demo.v1')).entries.filter(e => e.type === 'RSOT' && e.date === '2026-09-14').length === 1))
  await demo.getByRole('button', { name: 'Back to section' }).click()
  await demo.getByRole('button', { name: 'Training Dates', exact: true }).click()
  await demo.getByRole('button', { name: 'CHOOSE TRAINING', exact: true }).click()
  await demo.keyboard.press('Escape')
  check('Training chooser closes on Escape', await demo.getByRole('dialog').count() === 0)
  await demo.getByRole('button', { name: 'CHOOSE TRAINING', exact: true }).click()
  await demo.getByRole('button', { name: /HazMat Ops.*Add a sample/ }).click()
  check('Training chooser adds a local session', await demo.locator('.sim-event').filter({ hasText: 'HazMat Ops' }).isVisible())
  await demo.getByRole('button', { name: 'Settings', exact: true }).click()
  await demo.getByText('03 APPEARANCE', { exact: true }).click()
  await demo.getByRole('button', { name: /Edit Colors/ }).click()
  await demo.getByLabel('9x color', { exact: true }).fill('#123456')
  await demo.reload()
  await demo.getByRole('button', { name: 'Settings', exact: true }).click()
  await demo.getByText('03 APPEARANCE', { exact: true }).click()
  await demo.getByRole('button', { name: /Edit Colors/ }).click()
  check('Tour colors persist', await demo.getByLabel('9x color', { exact: true }).inputValue() === '#123456')
  await demo.getByRole('button', { name: 'Reset demo', exact: true }).click()
  await demo.keyboard.press('Escape')
  check('Reset dialog closes with Escape', await demo.getByRole('dialog').count() === 0)
  check('Reset trigger regains focus', await demo.getByRole('button', { name: 'Reset demo', exact: true }).evaluate(el => el === document.activeElement))
  await demo.getByRole('button', { name: 'Reset demo', exact: true }).click()
  await demo.getByRole('button', { name: 'Restore demo data' }).click()
  await demo.getByRole('button', { name: 'Dismiss sync warning' }).click()
  check('Reset restores seed calendar', await demo.locator('.sim-event').filter({ hasText: 'Vacation' }).count() === 0)
  await demo.getByRole('button', { name: 'Settings', exact: true }).click()
  await demo.getByText('01 IDENTITY & CREW', { exact: true }).click()
  check('Reset restores rank', await demo.getByRole('button', { name: 'Firefighter', exact: true }).getAttribute('aria-pressed') === 'true')
  await demo.getByRole('button', { name: 'Calendar', exact: true }).click()
  await demo.evaluate(() => document.fonts.ready)
  await demo.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await demo.screenshot({ path: 'artifacts/simulator-desktop.png', fullPage: true })
  check('Simulator has no desktop overflow', await demo.evaluate(() => document.documentElement.scrollWidth === innerWidth))
  for (const width of [320, 390]) {
    await demo.setViewportSize({ width, height: 844 })
    await demo.getByRole('button', { name: 'Full-screen demo', exact: true }).click()
    check(`Full screen fills the ${width}px viewport`, await demo.locator('.sim-fullscreen').evaluate(el => Math.abs(el.getBoundingClientRect().height - innerHeight) < 1))
    for (const tab of ['Calendar', 'Tracker', 'My Crew', 'Settings']) {
      await demo.getByRole('button', { name: tab, exact: true }).click()
      check(`${tab} navigation stays visible at ${width}px`, await demo.locator('.sim-bottom-tabs').evaluate(el => { const r = el.getBoundingClientRect(); return r.top >= 0 && r.bottom <= innerHeight }))
      check(`Simulator ${tab} has no ${width}px overflow`, await demo.evaluate(() => document.documentElement.scrollWidth === innerWidth))
    }
    await demo.getByRole('button', { name: 'Calendar', exact: true }).click()
    await demo.getByRole('button', { name: 'YEAR', exact: true }).click()
    check(`Year calendar has no ${width}px overflow`, await demo.evaluate(() => document.documentElement.scrollWidth === innerWidth))
    await demo.getByRole('button', { name: 'MONTH', exact: true }).click()
    check(`Month calendar has no ${width}px overflow`, await demo.evaluate(() => document.documentElement.scrollWidth === innerWidth))
    await demo.locator('.sim-screen').evaluate(el => { el.scrollTop = 250 })
    check(`Month controls remain pinned at ${width}px`, await demo.locator('.sim-calendar-controls').evaluate(el => Math.abs(el.getBoundingClientRect().top - el.closest('.sim-screen').getBoundingClientRect().top) < 2))
    await demo.locator('.sim-screen').evaluate(el => { el.scrollTop = 0 })
    await demo.locator('.sim-reference-day').first().click()
    check(`Day details form a bottom sheet at ${width}px`, await demo.getByRole('dialog').evaluate(el => { const r = el.getBoundingClientRect(); return Math.abs(r.bottom - innerHeight) < 2 && r.width === innerWidth }))
    await demo.getByRole('dialog').screenshot({ path: `artifacts/simulator-day-sheet-${width}.png` })
    await demo.keyboard.press('Escape')
    await demo.locator('.sim-device').screenshot({ path: `artifacts/simulator-month-${width}.png` })
    await demo.getByRole('button', { name: 'Reset demo', exact: true }).click()
    check('Reset remains available in full screen', await demo.getByRole('dialog').isVisible())
    await demo.getByRole('button', { name: 'Keep exploring' }).click()
    await demo.getByRole('button', { name: 'Exit full screen' }).click()
    check('Exit restores the website and launch button focus', await demo.getByRole('button', { name: 'Full-screen demo', exact: true }).evaluate(el => el === document.activeElement && !document.body.classList.contains('sim-fullscreen-active')))
    await demo.getByRole('button', { name: 'WEEK', exact: true }).click()
    await demo.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
    await demo.screenshot({ path: `artifacts/simulator-${width}.png`, fullPage: true })
  }
  check('Simulator makes no external requests', externalRequests.length === 0)
  check('Simulator makes no backend requests', backendRequests.length === 0)
  console.log('RESULT:', failures.length ? failures : 'All checks passed')
} finally { await browser.close(); server.close() }
if (failures.length) process.exitCode = 1
